version: 0.1
phases:
  install:
    commands:
      - apt-get update
      - apt-get install zip
      - npm install
      - npm install -g serverless
  pre_build:
    commands:
      - pip install virtualenv
      - virtualenv env
      - . env/bin/activate
      - pip install -r requirements.txt
      build:
    commands:
      - serverless deploy --stage cicd | tee deploy.out
  # post_build:
    # commands:
    #   - . ./test.sh
