version: 0.2
phases:
  install:
    commands:
      - apt-get update
      - apt-get install zip
      - npm install --silent --no-progress -g npm
      - npm install --silent --no-progress -g serverless
  pre_build:
    commands:
      - npm install --silent --no-progress
      - pip3 install -r requirements.txt
  build:
    commands:
      - sls plugin install -n serverless-python-requirements
      - sls plugin install -n serverless-deployment-bucket
      - serverless package --stage $ENVIRONMENT_STAGE --region $AWS_REGION
  post_build:
    commands:
      - serverless deploy --stage $ENVIRONMENT_STAGE --region $AWS_REGION
  artifacts:
    files:
      - '**/*''
      - serverless.yml
      name: kyc_api_functions-$ENVIRONMENT_STAGE-$(date +%Y-%m-%d)
      
