#
# For full config options, check the docs:
#    docs.serverless.com

service: bananacrystal-kyc-api

frameworkVersion: '2'

plugins:
  - serverless-python-requirements
  - serverless-deployment-bucket
provider:
  name: aws
  runtime: python3.8
  timeout: 60
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${opt:stage, self:provider.stage, 'dev'}}
  region: us-east-2
  deploymentBucket:
    name: codebuild-us-east-2-bananacrystal-dev-input-bucket
    serverSideEncryption: AES256

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: 'arn:aws:s3:::${self:custom.bucket}/*'
 
# package:
#   artifact: .serverless/bananacrystal-kyc-api.zip

custom:
  bucket: bananacrystal-kyc-api-aml-bucket-${opt:stage, self:provider.stage, 'dev'}
  defaultStage: dev
  profiles:
    dev: bananacrystal-dev
    prod: bananacrystal-prod      

functions:
  amlcheck:
    handler: handler.amlcheck
    description: This function will check name,id, and email against ofac sanction lists
    timeout: 60
    events:
      - http:
          path: amlcheck
          method: get
          cors: true
    environment:
      BUCKET: ${self:custom.bucket}


